EAZYBI-5311 MySQL 8.* JDBC driver failing because issue updated_at_utc time is in the 'lost hour' of daylight saving.
eazybi/activerecord-jdbc-adapter pull request #1
Opened 2023-10-16 09:51 UTC by jjustaments

2023-10-16 12:30 UTC, rsim requested changes
Please include also `arjdbc.postgresql.PostgreSQLRubyJdbcConnection` patch and replace the constant `TZ_DEFAULT` with dynamic `TimeZone.getDefault()`

2023-10-16 12:30 UTC, rsim commented on README_EAZYBI.md
> +4. Run the `bundle` command with the specified ActiveRecord version
Add a blank line as above

2023-10-17 14:49 UTC, jbaiza approved these changes
Looks good

2023-10-18 10:09 UTC, rsim approved these changes

2023-10-18 10:09 UTC, merged